version: '3'

services:
  excelapp:
    build: .
    container_name: excel-processor
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./templates:/app/templates
      - ./aggregations:/app/aggregations
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1 